// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package wesleyfrontendiface provides an interface to enable mocking the A beautiful and amazing AWSWesleyFrontend service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package wesleyfrontendiface

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/wesleyfrontend"
)

// WesleyFrontendAPI provides an interface to enable mocking the
// wesleyfrontend.WesleyFrontend service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // A beautiful and amazing AWSWesleyFrontend.
//    func myFunc(svc wesleyfrontendiface.WesleyFrontendAPI) bool {
//        // Make svc.AssociateEncryptionConfig request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := wesleyfrontend.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockWesleyFrontendClient struct {
//        wesleyfrontendiface.WesleyFrontendAPI
//    }
//    func (m *mockWesleyFrontendClient) AssociateEncryptionConfig(input *wesleyfrontend.AssociateEncryptionConfigInput) (*wesleyfrontend.AssociateEncryptionConfigOutput, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockWesleyFrontendClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type WesleyFrontendAPI interface {
	AssociateEncryptionConfig(*wesleyfrontend.AssociateEncryptionConfigInput) (*wesleyfrontend.AssociateEncryptionConfigOutput, error)
	AssociateEncryptionConfigWithContext(aws.Context, *wesleyfrontend.AssociateEncryptionConfigInput, ...request.Option) (*wesleyfrontend.AssociateEncryptionConfigOutput, error)
	AssociateEncryptionConfigRequest(*wesleyfrontend.AssociateEncryptionConfigInput) (*request.Request, *wesleyfrontend.AssociateEncryptionConfigOutput)

	AssociateIdentityProviderConfig(*wesleyfrontend.AssociateIdentityProviderConfigInput) (*wesleyfrontend.AssociateIdentityProviderConfigOutput, error)
	AssociateIdentityProviderConfigWithContext(aws.Context, *wesleyfrontend.AssociateIdentityProviderConfigInput, ...request.Option) (*wesleyfrontend.AssociateIdentityProviderConfigOutput, error)
	AssociateIdentityProviderConfigRequest(*wesleyfrontend.AssociateIdentityProviderConfigInput) (*request.Request, *wesleyfrontend.AssociateIdentityProviderConfigOutput)

	CreateAddon(*wesleyfrontend.CreateAddonInput) (*wesleyfrontend.CreateAddonOutput, error)
	CreateAddonWithContext(aws.Context, *wesleyfrontend.CreateAddonInput, ...request.Option) (*wesleyfrontend.CreateAddonOutput, error)
	CreateAddonRequest(*wesleyfrontend.CreateAddonInput) (*request.Request, *wesleyfrontend.CreateAddonOutput)

	CreateCluster(*wesleyfrontend.CreateClusterInput) (*wesleyfrontend.CreateClusterOutput, error)
	CreateClusterWithContext(aws.Context, *wesleyfrontend.CreateClusterInput, ...request.Option) (*wesleyfrontend.CreateClusterOutput, error)
	CreateClusterRequest(*wesleyfrontend.CreateClusterInput) (*request.Request, *wesleyfrontend.CreateClusterOutput)

	CreateFargateProfile(*wesleyfrontend.CreateFargateProfileInput) (*wesleyfrontend.CreateFargateProfileOutput, error)
	CreateFargateProfileWithContext(aws.Context, *wesleyfrontend.CreateFargateProfileInput, ...request.Option) (*wesleyfrontend.CreateFargateProfileOutput, error)
	CreateFargateProfileRequest(*wesleyfrontend.CreateFargateProfileInput) (*request.Request, *wesleyfrontend.CreateFargateProfileOutput)

	CreateNodegroup(*wesleyfrontend.CreateNodegroupInput) (*wesleyfrontend.CreateNodegroupOutput, error)
	CreateNodegroupWithContext(aws.Context, *wesleyfrontend.CreateNodegroupInput, ...request.Option) (*wesleyfrontend.CreateNodegroupOutput, error)
	CreateNodegroupRequest(*wesleyfrontend.CreateNodegroupInput) (*request.Request, *wesleyfrontend.CreateNodegroupOutput)

	DeleteAddon(*wesleyfrontend.DeleteAddonInput) (*wesleyfrontend.DeleteAddonOutput, error)
	DeleteAddonWithContext(aws.Context, *wesleyfrontend.DeleteAddonInput, ...request.Option) (*wesleyfrontend.DeleteAddonOutput, error)
	DeleteAddonRequest(*wesleyfrontend.DeleteAddonInput) (*request.Request, *wesleyfrontend.DeleteAddonOutput)

	DeleteCluster(*wesleyfrontend.DeleteClusterInput) (*wesleyfrontend.DeleteClusterOutput, error)
	DeleteClusterWithContext(aws.Context, *wesleyfrontend.DeleteClusterInput, ...request.Option) (*wesleyfrontend.DeleteClusterOutput, error)
	DeleteClusterRequest(*wesleyfrontend.DeleteClusterInput) (*request.Request, *wesleyfrontend.DeleteClusterOutput)

	DeleteFargateProfile(*wesleyfrontend.DeleteFargateProfileInput) (*wesleyfrontend.DeleteFargateProfileOutput, error)
	DeleteFargateProfileWithContext(aws.Context, *wesleyfrontend.DeleteFargateProfileInput, ...request.Option) (*wesleyfrontend.DeleteFargateProfileOutput, error)
	DeleteFargateProfileRequest(*wesleyfrontend.DeleteFargateProfileInput) (*request.Request, *wesleyfrontend.DeleteFargateProfileOutput)

	DeleteNodegroup(*wesleyfrontend.DeleteNodegroupInput) (*wesleyfrontend.DeleteNodegroupOutput, error)
	DeleteNodegroupWithContext(aws.Context, *wesleyfrontend.DeleteNodegroupInput, ...request.Option) (*wesleyfrontend.DeleteNodegroupOutput, error)
	DeleteNodegroupRequest(*wesleyfrontend.DeleteNodegroupInput) (*request.Request, *wesleyfrontend.DeleteNodegroupOutput)

	DescribeAddon(*wesleyfrontend.DescribeAddonInput) (*wesleyfrontend.DescribeAddonOutput, error)
	DescribeAddonWithContext(aws.Context, *wesleyfrontend.DescribeAddonInput, ...request.Option) (*wesleyfrontend.DescribeAddonOutput, error)
	DescribeAddonRequest(*wesleyfrontend.DescribeAddonInput) (*request.Request, *wesleyfrontend.DescribeAddonOutput)

	DescribeAddonVersions(*wesleyfrontend.DescribeAddonVersionsInput) (*wesleyfrontend.DescribeAddonVersionsOutput, error)
	DescribeAddonVersionsWithContext(aws.Context, *wesleyfrontend.DescribeAddonVersionsInput, ...request.Option) (*wesleyfrontend.DescribeAddonVersionsOutput, error)
	DescribeAddonVersionsRequest(*wesleyfrontend.DescribeAddonVersionsInput) (*request.Request, *wesleyfrontend.DescribeAddonVersionsOutput)

	DescribeCluster(*wesleyfrontend.DescribeClusterInput) (*wesleyfrontend.DescribeClusterOutput, error)
	DescribeClusterWithContext(aws.Context, *wesleyfrontend.DescribeClusterInput, ...request.Option) (*wesleyfrontend.DescribeClusterOutput, error)
	DescribeClusterRequest(*wesleyfrontend.DescribeClusterInput) (*request.Request, *wesleyfrontend.DescribeClusterOutput)

	DescribeFargateProfile(*wesleyfrontend.DescribeFargateProfileInput) (*wesleyfrontend.DescribeFargateProfileOutput, error)
	DescribeFargateProfileWithContext(aws.Context, *wesleyfrontend.DescribeFargateProfileInput, ...request.Option) (*wesleyfrontend.DescribeFargateProfileOutput, error)
	DescribeFargateProfileRequest(*wesleyfrontend.DescribeFargateProfileInput) (*request.Request, *wesleyfrontend.DescribeFargateProfileOutput)

	DescribeIdentityProviderConfig(*wesleyfrontend.DescribeIdentityProviderConfigInput) (*wesleyfrontend.DescribeIdentityProviderConfigOutput, error)
	DescribeIdentityProviderConfigWithContext(aws.Context, *wesleyfrontend.DescribeIdentityProviderConfigInput, ...request.Option) (*wesleyfrontend.DescribeIdentityProviderConfigOutput, error)
	DescribeIdentityProviderConfigRequest(*wesleyfrontend.DescribeIdentityProviderConfigInput) (*request.Request, *wesleyfrontend.DescribeIdentityProviderConfigOutput)

	DescribeNodegroup(*wesleyfrontend.DescribeNodegroupInput) (*wesleyfrontend.DescribeNodegroupOutput, error)
	DescribeNodegroupWithContext(aws.Context, *wesleyfrontend.DescribeNodegroupInput, ...request.Option) (*wesleyfrontend.DescribeNodegroupOutput, error)
	DescribeNodegroupRequest(*wesleyfrontend.DescribeNodegroupInput) (*request.Request, *wesleyfrontend.DescribeNodegroupOutput)

	DescribeUpdate(*wesleyfrontend.DescribeUpdateInput) (*wesleyfrontend.DescribeUpdateOutput, error)
	DescribeUpdateWithContext(aws.Context, *wesleyfrontend.DescribeUpdateInput, ...request.Option) (*wesleyfrontend.DescribeUpdateOutput, error)
	DescribeUpdateRequest(*wesleyfrontend.DescribeUpdateInput) (*request.Request, *wesleyfrontend.DescribeUpdateOutput)

	DisassociateIdentityProviderConfig(*wesleyfrontend.DisassociateIdentityProviderConfigInput) (*wesleyfrontend.DisassociateIdentityProviderConfigOutput, error)
	DisassociateIdentityProviderConfigWithContext(aws.Context, *wesleyfrontend.DisassociateIdentityProviderConfigInput, ...request.Option) (*wesleyfrontend.DisassociateIdentityProviderConfigOutput, error)
	DisassociateIdentityProviderConfigRequest(*wesleyfrontend.DisassociateIdentityProviderConfigInput) (*request.Request, *wesleyfrontend.DisassociateIdentityProviderConfigOutput)

	ListAddons(*wesleyfrontend.ListAddonsInput) (*wesleyfrontend.ListAddonsOutput, error)
	ListAddonsWithContext(aws.Context, *wesleyfrontend.ListAddonsInput, ...request.Option) (*wesleyfrontend.ListAddonsOutput, error)
	ListAddonsRequest(*wesleyfrontend.ListAddonsInput) (*request.Request, *wesleyfrontend.ListAddonsOutput)

	ListClusters(*wesleyfrontend.ListClustersInput) (*wesleyfrontend.ListClustersOutput, error)
	ListClustersWithContext(aws.Context, *wesleyfrontend.ListClustersInput, ...request.Option) (*wesleyfrontend.ListClustersOutput, error)
	ListClustersRequest(*wesleyfrontend.ListClustersInput) (*request.Request, *wesleyfrontend.ListClustersOutput)

	ListClustersPages(*wesleyfrontend.ListClustersInput, func(*wesleyfrontend.ListClustersOutput, bool) bool) error
	ListClustersPagesWithContext(aws.Context, *wesleyfrontend.ListClustersInput, func(*wesleyfrontend.ListClustersOutput, bool) bool, ...request.Option) error

	ListFargateProfiles(*wesleyfrontend.ListFargateProfilesInput) (*wesleyfrontend.ListFargateProfilesOutput, error)
	ListFargateProfilesWithContext(aws.Context, *wesleyfrontend.ListFargateProfilesInput, ...request.Option) (*wesleyfrontend.ListFargateProfilesOutput, error)
	ListFargateProfilesRequest(*wesleyfrontend.ListFargateProfilesInput) (*request.Request, *wesleyfrontend.ListFargateProfilesOutput)

	ListFargateProfilesPages(*wesleyfrontend.ListFargateProfilesInput, func(*wesleyfrontend.ListFargateProfilesOutput, bool) bool) error
	ListFargateProfilesPagesWithContext(aws.Context, *wesleyfrontend.ListFargateProfilesInput, func(*wesleyfrontend.ListFargateProfilesOutput, bool) bool, ...request.Option) error

	ListIdentityProviderConfigs(*wesleyfrontend.ListIdentityProviderConfigsInput) (*wesleyfrontend.ListIdentityProviderConfigsOutput, error)
	ListIdentityProviderConfigsWithContext(aws.Context, *wesleyfrontend.ListIdentityProviderConfigsInput, ...request.Option) (*wesleyfrontend.ListIdentityProviderConfigsOutput, error)
	ListIdentityProviderConfigsRequest(*wesleyfrontend.ListIdentityProviderConfigsInput) (*request.Request, *wesleyfrontend.ListIdentityProviderConfigsOutput)

	ListNodegroups(*wesleyfrontend.ListNodegroupsInput) (*wesleyfrontend.ListNodegroupsOutput, error)
	ListNodegroupsWithContext(aws.Context, *wesleyfrontend.ListNodegroupsInput, ...request.Option) (*wesleyfrontend.ListNodegroupsOutput, error)
	ListNodegroupsRequest(*wesleyfrontend.ListNodegroupsInput) (*request.Request, *wesleyfrontend.ListNodegroupsOutput)

	ListNodegroupsPages(*wesleyfrontend.ListNodegroupsInput, func(*wesleyfrontend.ListNodegroupsOutput, bool) bool) error
	ListNodegroupsPagesWithContext(aws.Context, *wesleyfrontend.ListNodegroupsInput, func(*wesleyfrontend.ListNodegroupsOutput, bool) bool, ...request.Option) error

	ListTagsForResource(*wesleyfrontend.ListTagsForResourceInput) (*wesleyfrontend.ListTagsForResourceOutput, error)
	ListTagsForResourceWithContext(aws.Context, *wesleyfrontend.ListTagsForResourceInput, ...request.Option) (*wesleyfrontend.ListTagsForResourceOutput, error)
	ListTagsForResourceRequest(*wesleyfrontend.ListTagsForResourceInput) (*request.Request, *wesleyfrontend.ListTagsForResourceOutput)

	ListUpdates(*wesleyfrontend.ListUpdatesInput) (*wesleyfrontend.ListUpdatesOutput, error)
	ListUpdatesWithContext(aws.Context, *wesleyfrontend.ListUpdatesInput, ...request.Option) (*wesleyfrontend.ListUpdatesOutput, error)
	ListUpdatesRequest(*wesleyfrontend.ListUpdatesInput) (*request.Request, *wesleyfrontend.ListUpdatesOutput)

	ListUpdatesPages(*wesleyfrontend.ListUpdatesInput, func(*wesleyfrontend.ListUpdatesOutput, bool) bool) error
	ListUpdatesPagesWithContext(aws.Context, *wesleyfrontend.ListUpdatesInput, func(*wesleyfrontend.ListUpdatesOutput, bool) bool, ...request.Option) error

	TagResource(*wesleyfrontend.TagResourceInput) (*wesleyfrontend.TagResourceOutput, error)
	TagResourceWithContext(aws.Context, *wesleyfrontend.TagResourceInput, ...request.Option) (*wesleyfrontend.TagResourceOutput, error)
	TagResourceRequest(*wesleyfrontend.TagResourceInput) (*request.Request, *wesleyfrontend.TagResourceOutput)

	UntagResource(*wesleyfrontend.UntagResourceInput) (*wesleyfrontend.UntagResourceOutput, error)
	UntagResourceWithContext(aws.Context, *wesleyfrontend.UntagResourceInput, ...request.Option) (*wesleyfrontend.UntagResourceOutput, error)
	UntagResourceRequest(*wesleyfrontend.UntagResourceInput) (*request.Request, *wesleyfrontend.UntagResourceOutput)

	UpdateAddon(*wesleyfrontend.UpdateAddonInput) (*wesleyfrontend.UpdateAddonOutput, error)
	UpdateAddonWithContext(aws.Context, *wesleyfrontend.UpdateAddonInput, ...request.Option) (*wesleyfrontend.UpdateAddonOutput, error)
	UpdateAddonRequest(*wesleyfrontend.UpdateAddonInput) (*request.Request, *wesleyfrontend.UpdateAddonOutput)

	UpdateClusterConfig(*wesleyfrontend.UpdateClusterConfigInput) (*wesleyfrontend.UpdateClusterConfigOutput, error)
	UpdateClusterConfigWithContext(aws.Context, *wesleyfrontend.UpdateClusterConfigInput, ...request.Option) (*wesleyfrontend.UpdateClusterConfigOutput, error)
	UpdateClusterConfigRequest(*wesleyfrontend.UpdateClusterConfigInput) (*request.Request, *wesleyfrontend.UpdateClusterConfigOutput)

	UpdateClusterVersion(*wesleyfrontend.UpdateClusterVersionInput) (*wesleyfrontend.UpdateClusterVersionOutput, error)
	UpdateClusterVersionWithContext(aws.Context, *wesleyfrontend.UpdateClusterVersionInput, ...request.Option) (*wesleyfrontend.UpdateClusterVersionOutput, error)
	UpdateClusterVersionRequest(*wesleyfrontend.UpdateClusterVersionInput) (*request.Request, *wesleyfrontend.UpdateClusterVersionOutput)

	UpdateNodegroupConfig(*wesleyfrontend.UpdateNodegroupConfigInput) (*wesleyfrontend.UpdateNodegroupConfigOutput, error)
	UpdateNodegroupConfigWithContext(aws.Context, *wesleyfrontend.UpdateNodegroupConfigInput, ...request.Option) (*wesleyfrontend.UpdateNodegroupConfigOutput, error)
	UpdateNodegroupConfigRequest(*wesleyfrontend.UpdateNodegroupConfigInput) (*request.Request, *wesleyfrontend.UpdateNodegroupConfigOutput)

	UpdateNodegroupVersion(*wesleyfrontend.UpdateNodegroupVersionInput) (*wesleyfrontend.UpdateNodegroupVersionOutput, error)
	UpdateNodegroupVersionWithContext(aws.Context, *wesleyfrontend.UpdateNodegroupVersionInput, ...request.Option) (*wesleyfrontend.UpdateNodegroupVersionOutput, error)
	UpdateNodegroupVersionRequest(*wesleyfrontend.UpdateNodegroupVersionInput) (*request.Request, *wesleyfrontend.UpdateNodegroupVersionOutput)

	WaitUntilClusterActive(*wesleyfrontend.DescribeClusterInput) error
	WaitUntilClusterActiveWithContext(aws.Context, *wesleyfrontend.DescribeClusterInput, ...request.WaiterOption) error

	WaitUntilClusterDeleted(*wesleyfrontend.DescribeClusterInput) error
	WaitUntilClusterDeletedWithContext(aws.Context, *wesleyfrontend.DescribeClusterInput, ...request.WaiterOption) error

	WaitUntilNodegroupActive(*wesleyfrontend.DescribeNodegroupInput) error
	WaitUntilNodegroupActiveWithContext(aws.Context, *wesleyfrontend.DescribeNodegroupInput, ...request.WaiterOption) error

	WaitUntilNodegroupDeleted(*wesleyfrontend.DescribeNodegroupInput) error
	WaitUntilNodegroupDeletedWithContext(aws.Context, *wesleyfrontend.DescribeNodegroupInput, ...request.WaiterOption) error
}

var _ WesleyFrontendAPI = (*wesleyfrontend.WesleyFrontend)(nil)
