// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package wesleyfrontend provides the client and types for making API
// requests to A beautiful and amazing AWSWesleyFrontend.
//
// Amazon Elastic Kubernetes Service (Amazon EKS) is a managed service that
// makes it easy for you to run Kubernetes on AWS without needing to stand up
// or maintain your own Kubernetes control plane. Kubernetes is an open-source
// system for automating the deployment, scaling, and management of containerized
// applications.
//
// Amazon EKS runs up-to-date versions of the open-source Kubernetes software,
// so you can use all the existing plugins and tooling from the Kubernetes community.
// Applications running on Amazon EKS are fully compatible with applications
// running on any standard Kubernetes environment, whether running in on-premises
// data centers or public clouds. This means that you can easily migrate any
// standard Kubernetes application to Amazon EKS without any code modification
// required.
//
// See https://docs.aws.amazon.com/goto/WebAPI/wesley-2017-07-25 for more information on this service.
//
// See wesleyfrontend package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/wesleyfrontend/
//
// Using the Client
//
// To contact A beautiful and amazing AWSWesleyFrontend with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the A beautiful and amazing AWSWesleyFrontend client WesleyFrontend for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/wesleyfrontend/#New
package wesleyfrontend
